Repository stratisproject/StratisBitcoinFullNode, pull requests merged in 2018-08, with the labels that each got.

#1777 [RF] Move rules to NBitcoin.Consensus
  src/NBitcoin/Consensus.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/Rules/IConsensusRule.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PosConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PowConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRulesTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRulesExtension.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/FullNodeBuilderTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/ReflectionRuleRegistrationTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/ReflectionRuleRegistration.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/ReflectionVirtualMachineFeature.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractRuleRegistration.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin/Consensus/Rules/ConsensusRule.cs
  src/Stratis.Bitcoin/Consensus/Rules/ConsensusRules.cs
  src/Stratis.Bitcoin/Consensus/Rules/IConsensusRules.cs
  src/Stratis.Bitcoin/Consensus/Rules/IRuleRegistration.cs
Labels: pr-review-medium, sp1

#1723 CHT Issue 20.
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1749 CHT Issue 18. #1765
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1742 Begin making Consensus immutable
  src/NBitcoin/BIP9DeploymentsArray.cs
  src/NBitcoin/BuriedDeploymentsArray.cs
  src/NBitcoin/Consensus.cs
  src/NBitcoin/IConsensus.cs
  src/NBitcoin/Network.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsTest.cs
  src/Stratis.Bitcoin.Networks/BitcoinMain.cs
  src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs
  src/Stratis.Bitcoin.Networks/BitcoinTest.cs
  src/Stratis.Bitcoin.Networks/StratisMain.cs
  src/Stratis.Bitcoin.Networks/StratisRegTest.cs
  src/Stratis.Bitcoin.Networks/StratisTest.cs
Labels: pr-review-critical

#1778 Fix default MinRelayTxFee
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/Policy/StandardTransactionPolicy.cs
Labels: pr-review-high

#1772 Load NLog.config from the DataFolder
  src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
Labels: pr-review-low

#1649 Minor logic fix in MempoolBehavior for blockonly mode
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolOrphans.cs
Labels: pr-review-medium

#1806 Move DifficultyAdjustmentInterval calculation
  src/NBitcoin/ChainedHeader.cs
  src/NBitcoin/Consensus.cs
Labels: pr-review-medium

#1841 Update docs on NLog.config
  Documentation/using-logging.md
Labels: pr-review-low

#1829 [Activation] Shutdown sequence and bugfixes
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusStats.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTestsHelper.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
  src/Stratis.Bitcoin/Base/BaseFeature.cs
  src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/Connection/ConnectionManagerBehavior.cs
  src/Stratis.Bitcoin/Connection/IConnectionManager.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/Validators/BlockValidator.cs
  src/Stratis.Bitcoin/FullNode.cs
Labels: pr-review-high

#1825 Check if peer is banned and when refreshing masterfile
  src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
  src/Stratis.Bitcoin.Features.Dns.Tests/Stratis.Bitcoin.Features.Dns.Tests.csproj
  src/Stratis.Bitcoin.Features.Dns/DnsFeature.cs
  src/Stratis.Bitcoin.Features.Dns/IFullNodeBuilderExtensions.cs
  src/Stratis.Bitcoin.Features.Dns/WhitelistManager.cs
Labels: pr-review-medium

#1769 Stake split
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/StakeSplittingTests.cs
  src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
Labels: pr-review-high

#1827 After peer attempt time threshold expires reset counters (#1816)
  src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs
  src/Stratis.Bitcoin/P2P/PeerAddress.cs
  src/Stratis.Bitcoin/P2P/PeerSelector.cs
Labels: pr-review-medium

#1800 CHT Issue 28
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1844 Wallet Recovery Fix
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs
Labels: pr-review-medium

#1850 Fixes #1847 NodeSettings is initalized 3 times
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
Labels: pr-review-low

#1780 Posminting config
  src/Stratis.Bitcoin.Features.Miner.Tests/MinerSettingsTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner/MinerSettings.cs
  src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
  src/Stratis.Bitcoin/Configuration/TextFileConfiguration.cs
Labels: pr-review-medium

#1861 little reorg of the consensus manager file
  src/Stratis.Bitcoin/Consensus/BlockDownloadRequest.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/IConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ValidationResults/ConnectBlocksResult.cs
  src/Stratis.Bitcoin/Consensus/ValidationResults/PartialValidationResult.cs
  src/Stratis.Bitcoin/Consensus/ValidationResults/ValidationResult.cs
  src/Stratis.Bitcoin/Consensus/Validators/BlockValidator.cs
Labels: pr-review-medium

#1860 Improvements toTestHelper.Wait loop, increased wait time on Segwit test
  src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
  src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs
Labels: pr-review-low

#1842 Hide staking API when POW and mining API when POS
  src/Stratis.Bitcoin.Features.Api/Startup.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/MiningControllerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/StakingControllerTest.cs
  src/Stratis.Bitcoin.Features.Miner/Controllers/MiningController.cs
  src/Stratis.Bitcoin.Features.Miner/Controllers/StakingController.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
Labels: pr-review-medium

#1873 [SC] Abstract contract address generation
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletOnPosNetworkTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.SmartContracts.Core/NewContractAddressExtension.cs
  src/Stratis.SmartContracts.Executor.Reflection/AddressGenerator.cs
  src/Stratis.SmartContracts.Executor.Reflection/IAddressGenerator.cs
  src/Stratis.SmartContracts.Executor.Reflection/NewContractAddressExtension.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
Labels: smart-contracts

#1805 [Consensus] Block version calculation moved to rules
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BitcoinHeaderVersionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/HeaderVersionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/StratisHeaderVersionRule.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractPowRuleRegistration.cs
Labels: pr-review-critical

#1840 Add guidelines around rebasing PRs with conflicts
  Documentation/contributing.md
Labels: pr-review-low

#1875 [SC] Meter gas separately
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Lifecycle/SmartContractConstructorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Lifecycle/SmartContractRestorerTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatRule.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/CallContract.cs
  src/Stratis.SmartContracts.Core/Exceptions/InsufficientGasException.cs
  src/Stratis.SmartContracts.Core/Message.cs
  src/Stratis.SmartContracts.Executor.Reflection/Executor.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
  src/Stratis.SmartContracts/IMessage.cs
  src/Stratis.SmartContracts/TransferFundsToContract.cs
Labels: smart-contracts

#1879 [SC] PoS Smart Contract Network
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractPosRegTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractPosTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsTest.cs
  src/Stratis.StratisSmartContractsD/Program.cs
Labels: smart-contracts

#1870 [Activation] Implement BlockMined
  src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/PowMining.cs
  src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractLoadCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractSaveCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatRule.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/CoreNodeExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContextBuilder.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ConsensusRuleEngine.cs
  src/Stratis.Bitcoin/Consensus/IConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ValidationResults/ValidationResult.cs
  src/Stratis.Bitcoin/Consensus/Validators/BlockValidator.cs
  src/Stratis.Bitcoin/Primitives/ChainedHeaderBlock.cs
Labels: Activation

#1888 [SC] Small fixes to get SC POS network working
  src/Stratis.Bitcoin.Features.Consensus/ConsensusErrors.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractNetwork.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractPosRegTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractPosTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.StratisSmartContractsD/Properties/launchSettings.json
Labels: pr-review-low, smart-contracts

#1843 Use same Network in NodeGroupBuilder when creating nodes
  src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowApiRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisPosApiRunner.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/RPCTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
Labels: pr-review-low

#1901 [SC] Add IContract abstraction
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Lifecycle/SmartContractRestorerTests.cs
  src/Stratis.SmartContracts.Executor.Reflection/Contract.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractInvocationErrorType.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractInvocationResult.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContractInvocationResult.cs
  src/Stratis.SmartContracts.Executor.Reflection/Lifecycle/SmartContractRestorer.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
Labels: smart-contracts

#1895 Spending staking balance #1294
  src/Stratis.Bitcoin.Features.Miner/Models/GetStakingInfoModel.cs
  src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
Labels: pr-review-medium

#1915 Add trace logging to mempool feature
  src/Stratis.Bitcoin.Features.MemoryPool/Interfaces/ITxMempool.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolManager.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolPersistence.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs
Labels: pr-review-low

#1890 WalletSyncManager speedup with AsyncQueue<Block>
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletSyncManagerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletSyncManager.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
Labels: pr-review-medium

#1913 Implement support for returning transaction details in block #1912
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreControllerTests.cs
  src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs
  src/Stratis.Bitcoin.Features.BlockStore/Models/BlockTransactionDetailsModel.cs
  src/Stratis.Bitcoin.Features.BlockStore/Models/SearchByHashRequest.cs
Labels: pr-review-low

#1922 [SC] Abstract contract assembly loading functionality
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Loader/ContractAssemblyLoaderTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Loader/ContractAssemblyTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Loader/Test.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.SmartContracts.Executor.Reflection/Loader/ContractAssembly.cs
  src/Stratis.SmartContracts.Executor.Reflection/Loader/ContractAssemblyLoader.cs
  src/Stratis.SmartContracts.Executor.Reflection/Loader/ContractByteCode.cs
  src/Stratis.SmartContracts.Executor.Reflection/Loader/IContractAssembly.cs
  src/Stratis.SmartContracts.Executor.Reflection/Loader/ILoader.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
Labels: smart-contracts

#1935 [Activation] Fix syncing issue with block store behaviour
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BitcoinActivationRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BitcoinHeaderVersionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockMerkleRootRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockSizeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/StratisHeaderVersionRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractPosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractPosCoinviewRule.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
Labels: Activation

#1933 [SC] Remove SmartContractConstructor
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Lifecycle/SmartContractConstructorTests.cs
  src/Stratis.SmartContracts.Executor.Reflection/Contract.cs
  src/Stratis.SmartContracts.Executor.Reflection/Lifecycle/LifecycleResult.cs
  src/Stratis.SmartContracts.Executor.Reflection/Lifecycle/SmartContractConstructor.cs
  src/Stratis.SmartContracts.Executor.Reflection/Stratis.SmartContracts.Executor.Reflection.csproj
  src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
Labels: smart-contracts

#1943 [SC] Closes #1942 reuse ModuleDefinition
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractGasInjector.cs
Labels: smart-contracts

#1944 [SC] SmartContractDecompilation refactoring
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismErrorMessageTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/FormatValidationTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractCompilerTests.cs
  src/Stratis.SmartContracts.Core.Validation.Tests/SmartContractDeterminismValidatorTests.cs
  src/Stratis.SmartContracts.Core.Validation/ISmartContractValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractDecompilation.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractDeterminismValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractFormatValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractWarningValidator.cs
  src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractDecompiler.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractDecompilation.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractDecompilation.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractGasInjector.cs
  src/Stratis.SmartContracts.Tools.Sct/SctDeterminismValidator.cs
  src/Stratis.SmartContracts.Tools.Sct/Validation/Validator.cs
  src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
Labels: smart-contracts

#1760 [Wallet] Prevent spending of immature coins
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/CoreNodeExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/SharedSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletOnPosNetworkTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingStakedCoinsBeforeMaturity.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingStakedCoinsBeforeMaturity_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
Labels: pr-review-medium

#1955 [SC] Inject all overloads of a method with gas metering
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractGasInjector.cs
Labels: smart-contracts

#1956 [SC] Introduce IContractModuleDefinitionReader
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismErrorMessageTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/DeterminismValidationTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/FormatValidationTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractCompilerTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.SmartContracts.Core.Validation.Tests/SmartContractDeterminismValidatorTests.cs
  src/Stratis.SmartContracts.Executor.Reflection/Compilation/ContractModuleDefinitionReader.cs
  src/Stratis.SmartContracts.Executor.Reflection/Compilation/IContractModuleDefinitionReader.cs
  src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractDecompiler.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Tools.Sct/SctDeterminismValidator.cs
  src/Stratis.SmartContracts.Tools.Sct/Validation/Validator.cs
  src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
Labels: smart-contracts

#1946 Add delay & parallelise node connections
  src/Stratis.Bitcoin/P2P/PeerConnector.cs
  src/Stratis.Bitcoin/P2P/PeerConnectorAddNode.cs
  src/Stratis.Bitcoin/P2P/PeerConnectorConnect.cs
Labels: pr-review-medium

#1951 [Activation] Fix ChainState's IsAtBestTip
  src/Stratis.Bitcoin.Features.Miner/PowBlockDefinition.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
Labels: Activation

#1973 [Activation] Fix WalletCanReceiveAndSendCorrectly
  src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/CoreNodeExtensions.cs
Labels: Activation

#1900 MyVersion.AddressFrom is not initialized properly (#1816).
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTestsHelper.cs
  src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTestsHelper.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerBehaviourTests.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerTests.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerSelectorTests.cs
  src/Stratis.Bitcoin.Tests/P2P/SelfEndpointTrackerTests.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/P2P/ISelfEndpointTracker.cs
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnectionParameters.cs
  src/Stratis.Bitcoin/P2P/SelfEndpointTracker.cs
Labels: pr-review-medium

#1972 [SC] Dispose of ContractModuleDefinition
  src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractDecompiler.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
Labels: smart-contracts

#1897 Https Api endpoint
  src/Stratis.Bitcoin.Api.Tests/ApiSettingsTest.cs
  src/Stratis.Bitcoin.Api.Tests/ProgramTests.cs
  src/Stratis.Bitcoin.Api.Tests/Stratis.Bitcoin.Api.Tests.csproj
  src/Stratis.Bitcoin.Features.Api/ApiFeature.cs
  src/Stratis.Bitcoin.Features.Api/ApiSettings.cs
  src/Stratis.Bitcoin.Features.Api/CertificateStore.cs
  src/Stratis.Bitcoin.Features.Api/ICertificateStore.cs
  src/Stratis.Bitcoin.Features.Api/Program.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
Labels: pr-review-medium

#1964 [Activation] Remove gap situation related code in CM
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManagerBehavior.cs
Labels: Activation

#1976 [Activation] Fix mempool integration tests
  src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ValidationResults/ConnectBlocksResult.cs
Labels: Activation

#1987 [Activation] PowBlockDefinition - ensure we are calling validator cor…
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockDefinition.cs
Labels: pr-review-low

#1983 [SC] Saving logs inside contracts and reaching consensus with receipt root and logs bloom.
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/AuctionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractLogHolderTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Receipts/ReceiptSerializationTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractBlockDefinition.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractPosPowBlockDefinition.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/Auction.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ContractCreation.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ContractCreationTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.SmartContracts.Core/ISmartContractExecutionResult.cs
  src/Stratis.SmartContracts.Core/Receipts/Log.cs
  src/Stratis.SmartContracts.Core/Receipts/Receipt.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/ContractLogHolder.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/IContractLogHolder.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/RawLog.cs
  src/Stratis.SmartContracts.Executor.Reflection/Executor.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutorFactory.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionSmartContractExecutorFactory.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractExecutionResult.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractState.cs
  src/Stratis.SmartContracts.Executor.Reflection/VmExecutionResult.cs
  src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
  src/Stratis.SmartContracts/IContractLogger.cs
  src/Stratis.SmartContracts/ISmartContractState.cs
  src/Stratis.SmartContracts/SmartContract.cs
Labels: smart-contracts

#1985 [SC] Implement fallback functions
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodCallTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ReceiveHandlerContract.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
  src/Stratis.SmartContracts.Executor.Reflection/CallData.cs
  src/Stratis.SmartContracts.Executor.Reflection/Contract.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
  src/Stratis.SmartContracts.Executor.Reflection/MethodCall.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts/IInternalTransactionExecutor.cs
  src/Stratis.SmartContracts/SmartContract.cs
Labels: smart-contracts

#1998 [Activation] Fix a few API integration tests
  src/Stratis.Bitcoin.Features.Consensus/ConsensusController.cs
  src/Stratis.Bitcoin/Controllers/FeatureController.cs
Labels: Activation

#2019 [Activation] Fix all miner integration tests
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
Labels: Activation

#2023 [Activation] Core way activation
  src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTestsHelper.cs
Labels: Activation

#1992 Replaced all references to DateTime.Now and DateTime.UtcNow with DateTimeProvider
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
Labels: pr-review-medium

#1914 Add passphrase to wallet create and recover #1677
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
  src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChainNode.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/GetStakingInfoActionTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletOnPosNetworkTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingStakedCoinsBeforeMaturity_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
Labels: pr-review-medium

#2031 [Activation] Merge from master - 24082018
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/AuctionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractLogHolderTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/MethodCallTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Receipts/PersistentReceiptRepositoryTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Receipts/ReceiptSerializationTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionExtensions.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractBlockDefinition.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractPosPowBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/Auction.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ContractCreation.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ContractCreationTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ReceiveHandlerContract.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
  src/Stratis.SmartContracts.Core/ISmartContractExecutionResult.cs
  src/Stratis.SmartContracts.Core/Receipts/IReceiptRepository.cs
  src/Stratis.SmartContracts.Core/Receipts/Log.cs
  src/Stratis.SmartContracts.Core/Receipts/PersistentReceiptRepository.cs
  src/Stratis.SmartContracts.Core/Receipts/Receipt.cs
  src/Stratis.SmartContracts.Core/Receipts/ReceiptRepository.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallData.cs
  src/Stratis.SmartContracts.Executor.Reflection/Contract.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/ContractLogHolder.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/IContractLogHolder.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractLogging/RawLog.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/Executor.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/IContractModuleDefinition.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutorFactory.cs
  src/Stratis.SmartContracts.Executor.Reflection/MethodCall.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionSmartContractExecutorFactory.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractExecutionResult.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractState.cs
  src/Stratis.SmartContracts.Executor.Reflection/VmExecutionResult.cs
  src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
  src/Stratis.SmartContracts/IContractLogger.cs
  src/Stratis.SmartContracts/IInternalTransactionExecutor.cs
  src/Stratis.SmartContracts/ISmartContractState.cs
  src/Stratis.SmartContracts/SmartContract.cs
Labels: Activation

#2001 [SC] Unit test for contract upgradeability
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractUpgradeabilityTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Packages/1.0.0-TEST/Stratis.SmartContracts.dll
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Packages/4.0.0-TEST/Stratis.SmartContracts.dll
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Packages/netcoreapp2.1/System.Runtime.dll
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
  src/Stratis.SmartContracts/Stratis.SmartContracts.csproj
Labels: smart-contracts

#2035 [SC] Receipt retrieval via controller
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Receipts/PersistentReceiptRepositoryTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Receipts/ReceiptSerializationTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Models/ReceiptResponse.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractBlockDefinition.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChainNode.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.SmartContracts.Core/Receipts/Receipt.cs
Labels: smart-contracts

#2029 [Activation] Fix failing tests - TransactionLocktimeActivationRuleTest.
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/TransactionLocktimeActivationRuleTest.cs
Labels: Activation

#2021 [Activation] Fixed Notifications tests
  src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs
  src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
Labels: Activation

#2045 [Activation] Fixes for PowMiningTest
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
Labels: Activation

#2038 [SC] Remove unused fields on TransactionContext
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
  src/Stratis.SmartContracts.Core/ISmartContractTransactionContext.cs
  src/Stratis.SmartContracts.Core/SmartContractTransactionContext.cs
  src/Stratis.SmartContracts.Executor.Reflection/Executor.cs
Labels: smart-contracts

#2041 [SC] Remove magic number and fix last test
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
Labels: smart-contracts

#2042 [SC] Part of ongoing work to refactor integration tests
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChain.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChainNode.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/ContractCreationTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
Labels: smart-contracts

#2050 Fixed Stratis.Bitcoin.Features.Consensus.Tests.Rules.CommonRules
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/RulesRegistrationOrderTest.cs
Labels: Activation

#2013 Api js attack
  src/Stratis.Bitcoin.Features.Miner/Controllers/StakingController.cs
  src/Stratis.Bitcoin.Features.RPC.Tests/Controller/RPCControllerTest.cs
  src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs
  src/Stratis.Bitcoin.IntegrationTests/API/AllControllersTests.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
  src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
Labels: pr-review-medium

#2034 Validate Block Based On Public Key Extracted From CoinStake Output
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosBlockSignatureRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractPosBlockSignatureRule.cs
Labels: pr-review-critical

#2016 Bitcoin core integration test common lib fixes
  appveyor.yml
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/BitcoinCoreRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/NodeRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
Labels: pr-review-low

#2061 [Activation] Fixed some tests
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BitcoinActivationRule.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs
  src/Stratis.Bitcoin/BlockPulling/BlockPullerBehavior.cs
Labels: Activation

#2063 [Activation]Merge from master - 29082018
  appveyor.yml
  src/NBitcoin.Tests/NetworkTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosBlockSignatureRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.Miner/Controllers/StakingController.cs
  src/Stratis.Bitcoin.Features.RPC.Tests/Controller/RPCControllerTest.cs
  src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractPosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/BitcoinCoreRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/NodeRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPosRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
  src/Stratis.Bitcoin.IntegrationTests/API/AllControllersTests.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
  src/Stratis.Bitcoin.Networks/StratisMain.cs
  src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
Labels: Activation

#2043 [Activation] Witness requirments
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/WitnessCommitmentsRule.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTestsHelper.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs
  src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ValidationContext.cs
Labels: Activation

#2039 [SC] Byte serialization
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/AuctionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ByteArrayConversionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ContractLogHolderTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/PersistentStateSerializerTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/ByteArrayConversion.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/StorageDemo.cs
  src/Stratis.SmartContracts.Executor.Reflection/Exceptions/PersistentStateSerializationException.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/Serialization/ContractPrimitiveSerializer.cs
  src/Stratis.SmartContracts.Executor.Reflection/Serialization/IContractPrimitiveSerializer.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractState.cs
  src/Stratis.SmartContracts.Tools.Sct/ValidatorService.cs
  src/Stratis.SmartContracts/ISerializer.cs
  src/Stratis.SmartContracts/ISmartContractState.cs
  src/Stratis.SmartContracts/SmartContract.cs
Labels: smart-contracts

#2070 [Activation] Fix A_cut_off_miner_advanced_ahead_of_network_causes_reorg_on_reconnect
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/BitcoinCoreRunner.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/SharedSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
Labels: Activation

#2078 [Activation] Fix Sending_Coins_Before_Maturity_Fails
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisPosApiRunner.cs
  src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingStakedCoinsBeforeMaturity_Steps.cs
Labels: Activation

#2071 Tests improvements 1
  src/NBitcoin.Tests/NBitcoin.Tests.csproj
  src/Stratis.Bitcoin.Api.Tests/Stratis.Bitcoin.Api.Tests.csproj
  src/Stratis.Bitcoin.Features.Apps.Tests/Stratis.Bitcoin.Features.Apps.Tests.csproj
  src/Stratis.Bitcoin.Features.BlockStore.Tests/Stratis.Bitcoin.Features.BlockStore.Tests.csproj
  src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Stratis.Bitcoin.Features.Consensus.Tests.csproj
  src/Stratis.Bitcoin.Features.Dns.Tests/Stratis.Bitcoin.Features.Dns.Tests.csproj
  src/Stratis.Bitcoin.Features.LightWallet.Tests/Stratis.Bitcoin.Features.LightWallet.Tests.csproj
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/Stratis.Bitcoin.Features.MemoryPool.Tests.csproj
  src/Stratis.Bitcoin.Features.Miner.Tests/Stratis.Bitcoin.Features.Miner.Tests.csproj
  src/Stratis.Bitcoin.Features.Notifications.Tests/Stratis.Bitcoin.Features.Notifications.Tests.csproj
  src/Stratis.Bitcoin.Features.RPC.Tests/Stratis.Bitcoin.Features.RPC.Tests.csproj
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
  src/Stratis.Bitcoin.Features.Wallet.Tests/Stratis.Bitcoin.Features.Wallet.Tests.csproj
  src/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests.csproj
  src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
  src/Stratis.Bitcoin.Tests.Common/Stratis.Bitcoin.Tests.Common.csproj
  src/Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj
  src/Stratis.Bitcoin/Base/ChainRepository.cs
  src/Stratis.BitcoinD/Stratis.BitcoinD.csproj
  src/Stratis.SmartContracts.Core.Validation.Tests/Stratis.SmartContracts.Core.Validation.Tests.csproj
  src/Stratis.SmartContracts.Core/Receipts/PersistentReceiptRepository.cs
  src/Stratis.StratisD/Stratis.StratisD.csproj
Labels: pr-review-low

#2052 Peer endpoint in validation context
  src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling/BlockPullerTests.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestContext.cs
  src/Stratis.Bitcoin/Base/BaseFeature.cs
  src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ConsensusRuleEngine.cs
  src/Stratis.Bitcoin/Consensus/IConsensusRuleEngine.cs
  src/Stratis.Bitcoin/Consensus/ValidationContext.cs
  src/Stratis.Bitcoin/Consensus/Validators/BlockValidator.cs
Labels: Activation

#2051 Listmethods return value
  src/Stratis.Bitcoin.Features.RPC.Tests/Controller/RPCControllerTest.cs
  src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs
Labels: pr-review-medium

#2083 [Activation] Fix smart contract integration tests #1
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractBlockDefinition.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
Labels: Activation
