Repository stratisproject/StratisBitcoinFullNode, pull requests merged in 2018-07, with the labels that each got.

#1577 [Bug] Null reference in BitcoinSerializableJsonConverter
  src/NBitcoin/IBitcoinSerializable.cs
  src/NBitcoin/JsonConverters/BitcoinSerializableJsonConverter.cs
  src/NBitcoin/JsonConverters/Serializer.cs
Labels: Urgent, bug, pr-review-critical

#1580 Back filling earlier tests Issue 1, 4 (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1565 Support deserialization of PosTransaction in WatchOnlyWallet
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWallet.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletManager.cs
Labels: pr-review-medium

#1576 Gap limit configurable
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
Labels: pr-review-low

#1543 Consensus manager part 3
  src/NBitcoin/ChainedHeader.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRulesTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRules.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/Connection/PeerBanning.cs
  src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManger.cs
  src/Stratis.Bitcoin/Consensus/Rules/ConsensusRules.cs
  src/Stratis.Bitcoin/Consensus/Rules/IConsensusRules.cs
  src/Stratis.Bitcoin/Consensus/Validators/BlockValidator.cs
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeerCollection.cs
  src/Stratis.Bitcoin/Primitives/ChainedHeaderBlock.cs
Labels: pr-review-critical

#1590 Wallet to use address buffer on startup
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility.cs
Labels: pr-review-low

#1575 CHT test: Race condition test - issue 29
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1578 Check BlockDataAvailabilityState is set correctly (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs
Labels: pr-review-low

#1593 Upgrade to dotnet 2.1
  .travis.yml
  appveyor.yml
  src/NBitcoin.Tests/NBitcoin.Tests.csproj
  src/NBitcoin/NBitcoin.csproj
  src/Stratis.Bitcoin.Api.Tests/Stratis.Bitcoin.Api.Tests.csproj
  src/Stratis.Bitcoin.Cli/Stratis.Bitcoin.Cli.csproj
  src/Stratis.Bitcoin.Features.Api/Stratis.Bitcoin.Features.Api.csproj
  src/Stratis.Bitcoin.Features.BlockStore.Tests/Stratis.Bitcoin.Features.BlockStore.Tests.csproj
  src/Stratis.Bitcoin.Features.BlockStore/Stratis.Bitcoin.Features.BlockStore.csproj
  src/Stratis.Bitcoin.Features.Consensus.Tests/Stratis.Bitcoin.Features.Consensus.Tests.csproj
  src/Stratis.Bitcoin.Features.Consensus/Stratis.Bitcoin.Features.Consensus.csproj
  src/Stratis.Bitcoin.Features.Dns.Tests/Stratis.Bitcoin.Features.Dns.Tests.csproj
  src/Stratis.Bitcoin.Features.Dns/Stratis.Bitcoin.Features.Dns.csproj
  src/Stratis.Bitcoin.Features.LightWallet.Tests/Stratis.Bitcoin.Features.LightWallet.Tests.csproj
  src/Stratis.Bitcoin.Features.LightWallet/Stratis.Bitcoin.Features.LightWallet.csproj
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/Stratis.Bitcoin.Features.MemoryPool.Tests.csproj
  src/Stratis.Bitcoin.Features.MemoryPool/Stratis.Bitcoin.Features.MemoryPool.csproj
  src/Stratis.Bitcoin.Features.Miner.Tests/Stratis.Bitcoin.Features.Miner.Tests.csproj
  src/Stratis.Bitcoin.Features.Miner/Stratis.Bitcoin.Features.Miner.csproj
  src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs
  src/Stratis.Bitcoin.Features.Notifications.Tests/Stratis.Bitcoin.Features.Notifications.Tests.csproj
  src/Stratis.Bitcoin.Features.Notifications/Stratis.Bitcoin.Features.Notifications.csproj
  src/Stratis.Bitcoin.Features.RPC.Tests/Stratis.Bitcoin.Features.RPC.Tests.csproj
  src/Stratis.Bitcoin.Features.RPC/Stratis.Bitcoin.Features.RPC.csproj
  src/Stratis.Bitcoin.Features.Wallet.Tests/Stratis.Bitcoin.Features.Wallet.Tests.csproj
  src/Stratis.Bitcoin.Features.Wallet/Stratis.Bitcoin.Features.Wallet.csproj
  src/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests.csproj
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Stratis.Bitcoin.Features.WatchOnlyWallet.csproj
  src/Stratis.Bitcoin.IntegrationTests.Common/Stratis.Bitcoin.IntegrationTests.Common.csproj
  src/Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.csproj
  src/Stratis.Bitcoin.Tests.Common/Stratis.Bitcoin.Tests.Common.csproj
  src/Stratis.Bitcoin.Tests.Wallet.Common/Stratis.Bitcoin.Tests.Wallet.Common.csproj
  src/Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj
  src/Stratis.Bitcoin/Stratis.Bitcoin.csproj
  src/Stratis.BitcoinD/Stratis.BitcoinD.csproj
  src/Stratis.BreezeD/Stratis.BreezeD.csproj
  src/Stratis.StratisD/Stratis.StratisD.csproj
  src/Stratis.StratisDnsD/Stratis.StratisDnsD.csproj
Labels: pr-review-high

#1574 BlockPuller tests
  src/Stratis.Bitcoin.Tests.Common/ReflectionExtensions.cs
  src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTestsHelper.cs
  src/Stratis.Bitcoin/BlockPulling2/BlockPuller.cs
  src/Stratis.Bitcoin/BlockPulling2/BlockPullerBehavior.cs
  src/Stratis.Bitcoin/BlockPulling2/DownloadJob.cs
Labels: pr-review-medium

#1600 Cleanup network usage in NBitcoin #3
  src/NBitcoin.Tests/ColoredCoinsTests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/Block.cs
  src/NBitcoin/JsonConverters/CoinJsonConverter.cs
  src/NBitcoin/OpenAsset/CoinprismColoredTransactionRepository.cs
  src/NBitcoin/OpenAsset/ColoredTransaction.cs
  src/NBitcoin/RPC/BlockExplorerFormatter.cs
  src/NBitcoin/RPC/RawFormatter.cs
  src/NBitcoin/RPC/SatoshiFormatter.cs
  src/NBitcoin/Transaction.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinMutableTests.cs
Labels: Refactor, improvement, pr-review-critical

#1611 remove-stash-file
  tash show p
Labels: pr-review-low

#1613 Update Dockerfile with 2.1 sdk
  Docker/Stratis.StratisD/Dockerfile
Labels: pr-review-low

#1599 Clean up Transaction usage in NBitcoin
  src/NBitcoin.Tests/ChainTests.cs
  src/NBitcoin.Tests/ColoredCoinsTests.cs
  src/NBitcoin.Tests/bloom_tests.cs
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/script_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/BlockStake.cs
  src/NBitcoin/ConsensusFactory.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/Networks/BitcoinMain.cs
  src/NBitcoin/Networks/BitcoinRegTest.cs
  src/NBitcoin/Networks/BitcoinTest.cs
  src/NBitcoin/Networks/StratisMain.cs
  src/NBitcoin/Networks/StratisRegTest.cs
  src/NBitcoin/Networks/StratisTest.cs
  src/NBitcoin/NoSqlRepository.cs
  src/NBitcoin/QBitNinjaTransactionRepository.cs
  src/NBitcoin/RPC/RPCClient.Wallet.cs
  src/NBitcoin/RPC/RPCClient.cs
  src/NBitcoin/RPC/RestClient.cs
  src/NBitcoin/Script.cs
  src/NBitcoin/Transaction.cs
  src/NBitcoin/TransactionBuilder.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderPosContextualRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosBlockSignatureRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/FeeTests.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
  src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet.Tests/WatchOnlyWalletManagerTest.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletManager.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MempoolRelaySpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
  src/Stratis.Bitcoin.Tests/Base/ChainRepositoryTest.cs
  src/Stratis.Bitcoin.Tests/Models/TransactionModelsTest.cs
Labels: Refactor, pr-review-critical

#1606 Connect new BlockPuller to ConsensusManager
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
Labels: pr-review-low

#1603 CHT finalized height bugfix
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
Labels: pr-review-low

#1607 CHT test: Enabling and disabling block store and checking data availability - issue 49 50
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1594 CHT test: Present chains with headers prior to checkpoint - issue 39
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs
Labels: pr-review-low

#1616 Cleanup network usage in NBitcoin #4
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/script_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/BloomFilter.cs
  src/NBitcoin/BuilderExtensions/P2MultiSigBuilderExtension.cs
  src/NBitcoin/BuilderExtensions/P2PKHBuilderExtension.cs
  src/NBitcoin/Coin.cs
  src/NBitcoin/Policy/StandardTransactionPolicy.cs
  src/NBitcoin/RPC/RestClient.cs
  src/NBitcoin/RPC/SatoshiFormatter.cs
  src/NBitcoin/Script.cs
  src/NBitcoin/StandardScriptTemplate.cs
  src/NBitcoin/StandardScripts.cs
  src/NBitcoin/Stealth/StealthMetadata.cs
  src/NBitcoin/Stealth/StealthPayment.cs
  src/NBitcoin/TransactionBuilder.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin/Controllers/Models/TransactionModel.cs
Labels: pr-review-high

#1583 Initial check-in Issue 12 (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1602 Issue 35 Initial check in (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1601 Initial commit Issue 34 (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1615 CHT test: Calling PartialValidationSucceeded for various scenarios - issue 51, 52 and 53
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1584 Initial commit Issue 31 (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1605 Cht tests fazzdev #1321 41
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1610 Issue 42 Initial check-in (#1321).
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1595 CHT test: Present 2 chains after the checkpoint - issue 40
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1623 Cleanup network usage in NBitcoin #5
  src/NBitcoin.Tests/ColoredCoinsTests.cs
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/script_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/BitcoinCore/CoinsView.cs
  src/NBitcoin/CachedNoSqlRepository.cs
  src/NBitcoin/InMemoryNoSqlRepository.cs
  src/NBitcoin/NoSqlRepository.cs
  src/NBitcoin/NoSqlTransactionRepository.cs
  src/NBitcoin/OpenAsset/NoSqlColoredTransactionRepository.cs
  src/NBitcoin/StandardScripts.cs
  src/NBitcoin/TransactionBuilder.cs
Labels: pr-review-critical

#1624 Cht tests fazzdev #1321 45
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1617 Issue 44 initial check-in (#1302).
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1585 Issue 32 initial commit (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1627 Cht tests fazzdev #1321 47
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1629 Cht tests fazzdev #1321 43
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1631 Converting entry points to asynchronous methods.
  src/Stratis.BitcoinD/Program.cs
  src/Stratis.BreezeD/Program.cs
  src/Stratis.StratisD/Program.cs
  src/Stratis.StratisDnsD/Program.cs
Labels: pr-review-medium

#1630 CM and CHT minor optimizations
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
Labels: pr-review-low

#1632 IDisposable for NetworkPeerBehavior
  src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
  src/Stratis.Bitcoin/P2P/Protocol/Behaviors/NetworkPeerBehavior.cs
  src/Stratis.Bitcoin/P2P/Protocol/Behaviors/NetworkPeerBehaviorsCollection.cs
  src/Stratis.Bitcoin/P2P/Protocol/Behaviors/PingPongBehavior.cs
Labels: pr-review-high

#1636 Simulate peer disconnection when resync is required
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
Labels: pr-review-low

#1643 Issue 55 initial commit (#1321).
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1634 [Mining] Add the ability to create proof of work blocks on a proof of stake network.
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/BlockProvider.cs
  src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
  src/Stratis.Bitcoin.Features.Miner/PosPowBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PowMining.cs
  src/Stratis.Bitcoin.IntegrationTests/ProofOfStakeSteps.cs
Labels: pr-review-critical

#1640 Cleanup network usage in NBitcoin #6
  src/NBitcoin.Tests/ChainTests.cs
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/Block.cs
  src/NBitcoin/ConcurrentChain.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreBehaviorTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PowCoinViewRuleTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletSyncManagerTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs
  src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
  src/Stratis.Bitcoin.Features.RPC/RPCClient.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletSyncManagerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.Tests.Wallet.Common/WalletTestsHelpers.cs
  src/Stratis.Bitcoin.Tests/Base/ChainRepositoryTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin/Base/BaseFeature.cs
Labels: pr-review-critical

#1638 CHB optimization
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs
  src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
  src/Stratis.Bitcoin/BlockPulling/BlockPuller.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
Labels: pr-review-high

#1642 Issue 54 initial clean commit (#1321).
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1650 Cleanup network usage in NBitcoin #7
  src/NBitcoin/QBitNinjaTransactionRepository.cs
Labels: pr-review-low

#1646 CHT tests: Sorted tests by issue #
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1644 Matching peers : PeerVersion can be null
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeerCollection.cs
Labels: pr-review-medium

#1647 peers in the list are not necessarily connected
  src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
Labels: pr-review-low

#1635 Fix for issue #1554 + missing API integration tests
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
  src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
  src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisBitcoinPowApiRunner.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
Labels: pr-review-medium

#1654 Fix compiler warnings and new Block() usage
  src/NBitcoin.Tests/ChainTests.cs
  src/NBitcoin.Tests/TestUtils.cs
  src/NBitcoin.Tests/checkblock_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/Utils.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreCacheTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderPowContextualRuleTest2.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderRuleTest2.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockSizeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CalculateStakeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CalculateWorkRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPosTransactionRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPowTransactionRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckSigOpsRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckpointsRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CoinbaseHeightRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/EnsureCoinbaseRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosCoinstakeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosFutureDriftRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PowCoinViewRuleTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/TransactionLocktimeActivationRuleTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/Notifications/BlockObserverTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/CustomRunner.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/ChainBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
  src/Stratis.Bitcoin.Tests.Common/TestBase.cs
  src/Stratis.Bitcoin.Tests.Wallet.Common/WalletTestsHelpers.cs
  src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTests.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
  src/Stratis.Bitcoin.Tests/Signals/SignalerTest.cs
  src/Stratis.Bitcoin.Tests/Signals/SignalsTest.cs
Labels: pr-review-low

#1596 Nodebuilder custom params
  src/Stratis.Bitcoin.Features.RPC/RPCClient.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Builders/NodeGroupBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNodeState.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeConfigParameters.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/FullNodeExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/CustomRunner.cs
  src/Stratis.Bitcoin.IntegrationTests/CustomNodeBuilderTests.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/RpcBitcoinMutableTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingStakedCoinsBeforeMaturity_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
Labels: pr-review-low

#1653 Consensus manager behavior (CHB refactoring)
  src/NBitcoin/BlockLocator.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
  src/Stratis.Bitcoin/Base/ConsensusManagerBehavior.cs
  src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/P2P/Protocol/Payloads/GetBlocksPayload.cs
  src/Stratis.Bitcoin/P2P/Protocol/Payloads/GetHeadersPayload.cs
Labels: pr-review-medium

#1658 [Integration Tests] Remove GenerateStratis
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/CoreNodeExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/CustomRunner.cs
  src/Stratis.Bitcoin.IntegrationTests/CustomNodeBuilderTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractNodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
Labels: pr-review-low

#1612 Connecting consensus rules
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderPowContextualRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderRuleTest2.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockMerkleRootRuleTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleDescriptorTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRulesTest.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.Consensus/RuleContextOverrides.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/AssumeValidRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderPosContextualRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderPowContextualRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockMerkleRootRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockSizeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CalculateStakeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CalculateWorkRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPosTransactionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckSigOpsRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckpointsRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinbaseHeightRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/EnsureCoinbaseRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/LoadCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockContextRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosCoinstakeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosFutureDriftRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PowCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/TransactionDuplicationActivationRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/TransactionLocktimeActivationRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/WitnessCommitmentsRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRules.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRulesExtension.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/ReflectionRuleRegistrationTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/OpSpendRuleTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/SmartContractFormatRuleTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/TxOutSmartContractExecRuleTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/MempoolOpSpendRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/OpSpendRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractLoadCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/TxOutSmartContractExecRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractConsensusRules.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/Rules/ConsensusRule.cs
  src/Stratis.Bitcoin/Consensus/Rules/ConsensusRules.cs
  src/Stratis.Bitcoin/Consensus/Rules/IConsensusRules.cs
  src/Stratis.Bitcoin/Consensus/Rules/RuleContext.cs
  src/Stratis.Bitcoin/Consensus/Validators/BlockValidator.cs
Labels: pr-review-medium

#1651 Feature plugins
  src/Stratis.Bitcoin.Apps.Browser/App.cshtml
  src/Stratis.Bitcoin.Apps.Browser/Dto/StratisApp.cs
  src/Stratis.Bitcoin.Apps.Browser/Interfaces/IAppsService.cs
  src/Stratis.Bitcoin.Apps.Browser/Pages/Index.cshtml
  src/Stratis.Bitcoin.Apps.Browser/Pages/_ViewImports.cshtml
  src/Stratis.Bitcoin.Apps.Browser/Program.cs
  src/Stratis.Bitcoin.Apps.Browser/Properties/launchSettings.json
  src/Stratis.Bitcoin.Apps.Browser/Services/AppsService.cs
  src/Stratis.Bitcoin.Apps.Browser/Shared/MainLayout.cshtml
  src/Stratis.Bitcoin.Apps.Browser/Shared/NavMenu.cshtml
  src/Stratis.Bitcoin.Apps.Browser/Stratis.Bitcoin.Apps.Browser.csproj
  src/Stratis.Bitcoin.Apps.Browser/_ViewImports.cshtml
  src/Stratis.Bitcoin.Apps.Browser/global.json
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/bootstrap/bootstrap.min.css
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/bootstrap/bootstrap.min.css.map
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/FONT-LICENSE
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/ICON-LICENSE
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/README.md
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/open-iconic/font/fonts/open-iconic.woff
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/css/site.css
  src/Stratis.Bitcoin.Apps.Browser/wwwroot/index.html
  src/Stratis.Bitcoin.Features.Apps.Tests/AppsHostTests.cs
  src/Stratis.Bitcoin.Features.Apps.Tests/FullNodeBuilderExtensionsTests.cs
  src/Stratis.Bitcoin.Features.Apps.Tests/Stratis.Bitcoin.Features.Apps.Tests.csproj
  src/Stratis.Bitcoin.Features.Apps/AppsController.cs
  src/Stratis.Bitcoin.Features.Apps/AppsFeature.cs
  src/Stratis.Bitcoin.Features.Apps/AppsHost.cs
  src/Stratis.Bitcoin.Features.Apps/AppsStore.cs
  src/Stratis.Bitcoin.Features.Apps/Interfaces/IAppsController.cs
  src/Stratis.Bitcoin.Features.Apps/Interfaces/IAppsHost.cs
  src/Stratis.Bitcoin.Features.Apps/Interfaces/IAppsStore.cs
  src/Stratis.Bitcoin.Features.Apps/Interfaces/IStratisApp.cs
  src/Stratis.Bitcoin.Features.Apps/SinglePageStartup.cs
  src/Stratis.Bitcoin.Features.Apps/Stratis.Bitcoin.Features.Apps.csproj
  src/Stratis.Bitcoin.Features.Apps/StratisApp.cs
  src/Stratis.Bitcoin.FullNode.sln
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
  src/Stratis.Bitcoin/Configuration/DataFolder.cs
  src/Stratis.Bitcoin/Utilities/IpHelper.cs
  src/Stratis.StratisD/Program.cs
  src/Stratis.StratisD/Stratis.StratisD.csproj
Labels: pr-review-high

#1661 [SC] Separate CallData deserialization
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/CallDataSerializerTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractCarrierTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractResultRefundProcessorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractResultTransferProcessorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/SmartContractScriptAddressReader.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallData.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallDataSerializer.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallSmartContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/CreateSmartContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/ICallDataSerializer.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractResultRefundProcessor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractResultTransferProcessor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionSmartContractExecutorFactory.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractCarrier.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractExecutionResult.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractResultRefundProcessor.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractResultTransferProcessor.cs
  src/Stratis.SmartContracts.Executor.Reflection/Stratis.SmartContracts.Executor.Reflection.csproj
Labels: smart-contracts

#1662 [Integration Tests] Fix GenerateBlockManually
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/CoreNodeExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractNodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
Labels: pr-review-low

#1674 [SC] Push executor functionality to VM
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Lifecycle/SmartContractConstructorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Lifecycle/SmartContractRestorerTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractVmBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallSmartContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/CreateSmartContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutorFactory.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionSmartContractExecutorFactory.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractExecutionContext.cs
  src/Stratis.SmartContracts.Executor.Reflection/VmExecutionResult.cs
Labels: smart-contracts

#1663 Made block signature validation rule non-skippable
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
Labels: pr-review-low

#1675 [SC] Remove SmartContractVmBuilder and SmartContractNetworkSimulator
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/SmartContractNetworkSimulator.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisSmartContractNode.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractNodeSyncTests.cs
  src/Stratis.StratisSmartContractsD/Program.cs
Labels: smart-contracts

#1680 [SC] Executor consolidation
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.SmartContracts.Executor.Reflection/Executor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionSmartContractExecutorFactory.cs
Labels: smart-contracts

#1679 CMB tests part 2 + added interface to connection manager behavior
  src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractNodeSyncTests.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTestsHelper.cs
  src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
  src/Stratis.Bitcoin/Base/ConsensusManagerBehavior.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/Connection/ConnectionManagerBehavior.cs
  src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs
  src/Stratis.Bitcoin/Connection/PeerBanning.cs
  src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
Labels: pr-review-low

#1659 do not AnnounceBlocks on null behaviors, Fix race condition expectation in MiningNodeWithOneConnectionAlwaysSynced, restore coinbase maturity after altering it in test
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreSignaled.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NetworkSimulator.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
  src/Stratis.Bitcoin/Utilities/AsyncExecutionEvent.cs
Labels: pr-review-medium

#1681 [SC] Precursor to creating contracts
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExecutorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/Auction.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/CallInfiniteLoopContract.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/ContractConstructorInvalid.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/ContractInvalidParameterCount.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/ContractMethodParameterTypeMismatch.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/InfiniteLoop.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/MultipleConstructor.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/OutOfGasTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/ThrowExceptionContract.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/Auction.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/CallContract.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/CountContract.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/InterContract1.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/InterContract2.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/StorageDemo.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/Token.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/TransferTest.cs
  src/Stratis.ModuleValidation.Net/TypesToIgnoreUtil.cs
  src/Stratis.SmartContracts.Core.Validation/SingleTypeValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractDeterminismValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractFormatValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractTypeDefinitionValidator.cs
  src/Stratis.SmartContracts.Core.Validation/SmartContractWarningValidator.cs
  src/Stratis.SmartContracts.Core/State/AccountState.cs
  src/Stratis.SmartContracts.Core/State/ContractStateRepository.cs
  src/Stratis.SmartContracts.Core/State/IContractStateRepository.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallSmartContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractDecompiler.cs
  src/Stratis.SmartContracts.Executor.Reflection/CreateSmartContract.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractGasInjector.cs
  src/Stratis.SmartContracts/DeployAttribute.cs
  src/Stratis.SmartContracts/ICreateResult.cs
  src/Stratis.SmartContracts/IInternalTransactionExecutor.cs
  src/Stratis.SmartContracts/SmartContract.cs
Labels: smart-contracts

#1700 [SC] Compile multiple files within a directory. Option to compile specific namespace.
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractCompilerTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/MultipleFiles1.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContracts/MultipleFiles2.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
  src/Stratis.SmartContracts.Executor.Reflection/Compilation/SmartContractCompiler.cs
Labels: smart-contracts

#1687 [SC] Separate CreateData and CallData
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/CallDataSerializerTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/GasInjectorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractExceptionTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractResultRefundProcessorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/SmartContractResultTransferProcessorTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatRule.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallData.cs
  src/Stratis.SmartContracts.Executor.Reflection/CallDataSerializer.cs
  src/Stratis.SmartContracts.Executor.Reflection/ContractTxData.cs
  src/Stratis.SmartContracts.Executor.Reflection/CreateData.cs
  src/Stratis.SmartContracts.Executor.Reflection/Executor.cs
  src/Stratis.SmartContracts.Executor.Reflection/IBaseContractTransactionData.cs
  src/Stratis.SmartContracts.Executor.Reflection/ICallData.cs
  src/Stratis.SmartContracts.Executor.Reflection/ICallDataSerializer.cs
  src/Stratis.SmartContracts.Executor.Reflection/ICreateData.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractResultRefundProcessor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractResultTransferProcessor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ISmartContractVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/InternalTransactionExecutor.cs
  src/Stratis.SmartContracts.Executor.Reflection/ReflectionVirtualMachine.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractCarrier.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractResultRefundProcessor.cs
  src/Stratis.SmartContracts.Executor.Reflection/SmartContractResultTransferProcessor.cs
Labels: smart-contracts

#1694 CMB tests part 4
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs
  src/Stratis.Bitcoin/Base/ConsensusManagerBehavior.cs
Labels: pr-review-low

#1682 [SC] Create Smart Contract Wallet / Clean up sc code in wallet classes.
  src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Wallet/SmartContractWalletController.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Wallet/SmartContractWalletExtensions.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Wallet/SmartContractWalletFeature.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Wallet/SmartContractWalletTransactionHandler.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Wallet/Stratis.Bitcoin.Features.SmartContracts.Wallet.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/SmartContractScriptAddressReader.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Controllers/SmartContractsController.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletExtensions.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
  src/Stratis.Bitcoin.FullNode.sln
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/MockChain/MockChain.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Runners/StratisSmartContractNode.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/SharedSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ProofOfWorkSpendingSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/ReorgToLongestChainSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractSharedSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractWalletTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingToAndFromManyAddressesSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletTests.cs
  src/Stratis.Bitcoin.Tests.Wallet.Common/WalletTestsHelpers.cs
  src/Stratis.Bitcoin/Utilities/ModelStateErrors/ModelStateErrors.cs
  src/Stratis.StratisSmartContractsD/Program.cs
Labels: pr-review-medium, smart-contracts

#1688 -reindex command now functions as expected.
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
Labels: pr-review-medium

#1704 ConsensusOptions per Network
  src/NBitcoin/Consensus.cs
  src/NBitcoin/ConsensusOptions.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/AssumeValidRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockSizeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPowTransactionRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckSigOpsRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockSizeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckSigOpsRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MemoryPoolTransactionTests.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolManagerTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolOrphans.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.MemoryPool/TxMemPoolEntry.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
Labels: pr-review-medium

#1713 Merge master into sc-dev
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreSignaled.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PeerBanningTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosBlockSignatureRule.cs
  src/Stratis.Bitcoin.Features.LightWallet/LightWalletFeature.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/CannotAddAccountToXpubKeyWalletException.cs
  src/Stratis.Bitcoin.Features.Wallet/Controllers/LegacyExtPubKeyConverter.cs
  src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
  src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs
  src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs
  src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs
  src/Stratis.Bitcoin.FullNode.sln
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NetworkSimulator.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractNodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs
  src/Stratis.Bitcoin.Tests.Common/ChainedHeadersHelper.cs
  src/Stratis.Bitcoin.Tests.Common/TestFramework/BddSpecification.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTestsHelper.cs
  src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTests.cs
  src/Stratis.Bitcoin.Tests/BlockPulling2/BlockPullerTestsHelper.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
  src/Stratis.Bitcoin/Base/ConsensusManagerBehavior.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/Connection/ConnectionManagerBehavior.cs
  src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs
  src/Stratis.Bitcoin/Connection/PeerBanning.cs
  src/Stratis.Bitcoin/Connection/PeerBanningBehavior.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnectionParameters.cs
  src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
  src/Stratis.Bitcoin/Utilities/AsyncExecutionEvent.cs
Labels: pr-review-low, smart-contracts

#1571 Assign all Consensus settings directly in inherited networks
  src/NBitcoin/Networks/BitcoinRegTest.cs
  src/NBitcoin/Networks/BitcoinTest.cs
  src/NBitcoin/Networks/StratisRegTest.cs
  src/NBitcoin/Networks/StratisTest.cs
Labels: pr-review-medium

#1720 [SC] Merge master into sc-dev
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin/Consensus.cs
  src/NBitcoin/ConsensusOptions.cs
  src/NBitcoin/Networks/BitcoinRegTest.cs
  src/NBitcoin/Networks/BitcoinTest.cs
  src/NBitcoin/Networks/StratisRegTest.cs
  src/NBitcoin/Networks/StratisTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/AssumeValidRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockSizeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPowTransactionRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckSigOpsRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockSizeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckSigOpsRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MemoryPoolTransactionTests.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolManagerTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolOrphans.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.MemoryPool/TxMemPoolEntry.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Mempool/MemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTests.cs
  src/Stratis.Bitcoin.Tests/Base/ConsensusManagerBehaviorTestsHelper.cs
  src/Stratis.Bitcoin/Base/ConsensusManagerBehavior.cs
Labels: pr-review-low, smart-contracts

#1683 Validator headers
  src/Stratis.Bitcoin.Features.Consensus.Tests/PosConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PowConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BitcoinActivationRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderPowContextualRuleTest2.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderRuleTest2.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CalculateStakeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CalculateWorkRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/HeaderTimeChecksRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosFutureDriftRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosTimeMaskRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/SetActivationDeploymentsRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRulesTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.Consensus/Interfaces/IStakeValidator.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BitcoinActivationRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderPowContextualRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CalculateWorkRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckDifficultyPosRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckDifficultyPowRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckDifficultykHybridRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/HeaderTimeChecksPosRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/HeaderTimeChecksRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/LoadCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosFutureDriftRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosTimeMaskRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/SetActivationDeploymentsRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/StratisHeaderVersionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Consensus/Rules/SmartContractLoadCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractRuleRegistration.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin/Consensus/Rules/RuleContext.cs
Labels: pr-review-high

#1660 Peer Discovery: Add filtering based on IP ranges #1216
  src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
  src/Stratis.Bitcoin/P2P/PeerConnector.cs
Labels: pr-review-medium

#1608 CHT Issue 19 & 6 Common test cases
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1717 Remove Consensus from ConsensusFactory
  src/NBitcoin/BitcoinCore/Coins.cs
  src/NBitcoin/Consensus.cs
  src/NBitcoin/ConsensusFactory.cs
  src/NBitcoin/Networks/StratisMain.cs
  src/NBitcoin/Networks/StratisRegTest.cs
  src/NBitcoin/Networks/StratisTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsTest.cs
  src/Stratis.Bitcoin/P2P/Protocol/Payloads/HeadersPayload.cs
Labels: pr-review-medium

#1721 Fixes for comments and warnings
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
Labels: pr-review-low

#1712 1397 fix race condition
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
Labels: pr-review-high

#1693 Remove node removes endpoint everywhere
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerAddressManagerTests.cs
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/Connection/IConnectionManager.cs
  src/Stratis.Bitcoin/FullNode.cs
  src/Stratis.Bitcoin/P2P/IPeerAddressManager.cs
  src/Stratis.Bitcoin/P2P/PeerAddressManager.cs
Labels: pr-review-medium

#1705 API Integration Test method naming redunancy fix
  src/Stratis.Bitcoin.Features.BlockStore/Models/BlockModel.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin/Controllers/Models/BlockHeaderModel.cs
  src/Stratis.Bitcoin/Controllers/Models/GetTxOutModel.cs
Labels: pr-review-medium

#1709 Remove pass-by-reference of Network in BitcoinAddress types
  src/NBitcoin/BitcoinAddress.cs
  src/NBitcoin/BitcoinPubKeyAddress.cs
  src/NBitcoin/BitcoinSegwitAddress.cs
  src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
Labels: pr-review-medium

#1691 Introduce the API feature to BitcoinD.
  src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/MiningApiControllerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/MiningRpcControllerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/StakingApiControllerTest.cs
  src/Stratis.Bitcoin.Features.Miner/Controllers/MiningApiController.cs
  src/Stratis.Bitcoin.Features.Miner/Controllers/MiningRPCController.cs
  src/Stratis.Bitcoin.Features.Miner/Controllers/StakingApiController.cs
  src/Stratis.Bitcoin.Features.Miner/Controllers/StakingRPCController.cs
  src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
  src/Stratis.Bitcoin.Features.Miner/Models/GenerateBlocksModel.cs
  src/Stratis.Bitcoin.Features.Miner/Models/RequestModels.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
  src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/GetStakingInfoActionTests.cs
  src/Stratis.BitcoinD/Program.cs
  src/Stratis.BitcoinD/Stratis.BitcoinD.csproj
Labels: pr-review-low

#1759 GetAccount was throwing a RPCServerException which is not correct.
  src/Stratis.Bitcoin.Features.Miner/Controllers/MiningApiController.cs
Labels: bug, pr-review-low

#1756 [SC] Executor contract creation specification
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/ExecutorSpecification.cs
Labels: smart-contracts

#1724 CM- signal 1 by one during the connection and extend signaler to have block disconnected signal
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.LightWallet.Tests/LightWalletSyncManagerTest.cs
  src/Stratis.Bitcoin.Features.LightWallet/LightWalletSyncManager.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs
  src/Stratis.Bitcoin.Features.Notifications.Tests/BlockNotificationTest.cs
  src/Stratis.Bitcoin.Features.Notifications/BlockNotification.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Wallet/SmartContractWalletFeature.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletFeature.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/WatchOnlyWalletFeature.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/GenerateCoinsFastDateTimeProvider.cs
  src/Stratis.Bitcoin.Tests/Signals/SignalsTest.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Signals/Signals.cs
Labels: pr-review-medium

#1770 Fix master build
  src/Stratis.Bitcoin.Tests/Signals/SignalsTest.cs
Labels: bug

#1739 Configure block size
  src/NBitcoin/ConsensusOptions.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockSizeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPowTransactionRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/MinerSettingsTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinitionOptions.cs
  src/Stratis.Bitcoin.Features.Miner/MinerSettings.cs
  src/Stratis.Bitcoin.Features.Miner/PosBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PosPowBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PowMining.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsRegTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Networks/SmartContractsTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractBlockDefinition.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/SmartContracts/SmartContractMinerTests.cs
  src/Stratis.Bitcoin.Networks/BitcoinMain.cs
  src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs
  src/Stratis.Bitcoin.Networks/BitcoinTest.cs
  src/Stratis.Bitcoin.Networks/StratisMain.cs
  src/Stratis.Bitcoin.Networks/StratisRegTest.cs
  src/Stratis.Bitcoin.Networks/StratisTest.cs
Labels: pr-review-critical

#1725 AppsFeature now ensures that the Stratis apps folder exists where ena…
  src/Stratis.Bitcoin.Features.Apps/AppsFeature.cs
Labels: pr-review-low
