Repository stratisproject/StratisBitcoinFullNode, pull requests merged in 2018-05, with the labels that each got.

#1361 [SmartContracts] Refactor Block Assemblers Part #2
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
  src/Stratis.Bitcoin.Features.Miner/PosBlockAssembler.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockAssembler.cs
  src/Stratis.Bitcoin.Features.Miner/PowMining.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
Labels: Refactor, improvement

#1387 [Smart Contracts] Refactor the block assemblers part 3
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner/AssemblerOptions.cs
  src/Stratis.Bitcoin.Features.Miner/BlockTemplate.cs
  src/Stratis.Bitcoin.Features.Miner/PosBlockAssembler.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockAssembler.cs
Labels: Refactor, improvement

#1393 Add GetBlocksAsync method to IBlockRepository
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryTest.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
Labels: pr-review-medium

#1394 Replacing NetworkOptions with TransactionOptions
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/BitcoinStream.cs
  src/NBitcoin/Block.cs
  src/NBitcoin/IBitcoinSerializable.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/NetworkOptions.cs
  src/NBitcoin/Networks.cs
  src/NBitcoin/Script.cs
  src/NBitcoin/Transaction.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockSizeRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPowTransactionRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.Consensus/PowConsensusValidator.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockSizeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolValidatorTest.cs
  src/Stratis.Bitcoin/BlockPulling/LookaheadBlockPuller.cs
  src/Stratis.Bitcoin/P2P/Peer/INetworkPeer.cs
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeer.cs
  src/Stratis.Bitcoin/P2P/Peer/NetworkPeerConnectionParameters.cs
Labels: pr-review-high

#1392 Fix some staking issues
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
Labels: pr-review-high

#1416 Add MaxOutboundConnections to ConnectionManagerSettings
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
  src/Stratis.Bitcoin/P2P/PeerConnectorDiscovery.cs
Labels: pr-review-low

#1412 Work on Networks part 1
  src/NBitcoin.Tests/NetworkBuilderTest.cs
  src/NBitcoin.Tests/NetworkTests.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/NetworkBuilder.cs
  src/NBitcoin/Networks.cs
  src/Stratis.Bitcoin.Tests/Utilities/NetworkHelpersTest.cs
Labels: pr-review-critical

#1408 DNS feature: Allow configuration file (and cmd line) to determine net…
  src/Stratis.StratisDnsD/Program.cs
Labels: pr-review-low

#1415 GetProofOfWorkRewardForMinedBlocks bug fix.
  src/Stratis.Bitcoin.IntegrationTests/Extensions/CoreNodeExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
Labels: pr-review-low

#1429 Ported listaccounts RPC call to the API
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs
  src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs
Labels: pr-review-low

#1417 Address GetDepthInMainChain TODO in PosMinting.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
Labels: pr-review-high

#1414 Pull out coinview validation rule
  src/NBitcoin/Network.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PosConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PowConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/BlockHeaderPosContextualRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PosFutureDriftRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PowCoinViewRuleTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusStats.cs
  src/Stratis.Bitcoin.Features.Consensus/IStakeChain.cs
  src/Stratis.Bitcoin.Features.Consensus/Interfaces/IConsensusLoop.cs
  src/Stratis.Bitcoin.Features.Consensus/Interfaces/IPosConsensusValidator.cs
  src/Stratis.Bitcoin.Features.Consensus/Interfaces/IPowConsensusValidator.cs
  src/Stratis.Bitcoin.Features.Consensus/PosConsensusValidator.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/BlockHeaderPosContextualRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosFutureDriftRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PowCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRules.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/IConsensusRules.cs
  src/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs
  src/Stratis.Bitcoin.Features.Consensus/StakeValidator.cs
  src/Stratis.Bitcoin.Features.Consensus/UnspentOutputSet.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/FullNodeBuilderTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolValidatorTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolOrphans.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner/PosBlockAssembler.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockAssembler.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Extensions/CoreNodeExtensions.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.IntegrationTests/Program.cs
  src/Stratis.Bitcoin/Configuration/Logging/NLog.config
Labels: pr-review-critical

#1405 #1214 #1176 Build Transaction bottleNeck
  src/NBitcoin/Key.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
  src/Stratis.Bitcoin/Utilities/Extensions/StringExtensions.cs
Labels: pr-review-medium

#1445 Added AddPayload method to PayloadProvider
  src/Stratis.Bitcoin/P2P/Protocol/Payloads/PayloadAttribute.cs
Labels: pr-review-low

#1440 Refactor block assemblers part 5
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/Stratis.Bitcoin.Features.Miner.Tests.csproj
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinitionOptions.cs
  src/Stratis.Bitcoin.Features.Miner/BlockProvider.cs
  src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
  src/Stratis.Bitcoin.Features.Miner/PosBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PowMining.cs
  src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/GenerateCoinsFastDateTimeProvider.cs
  src/Stratis.Bitcoin.IntegrationTests/EnvironmentMockUpHelpers/NodeRunners.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin/Mining/BlockTemplate.cs
  src/Stratis.Bitcoin/Mining/IBlockProvider.cs
Labels: Refactor, pr-review-high

#1452 Move "ConvertIpAddressToEndpoint" to IPExtensions.cs
  src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs
  src/Stratis.Bitcoin.Tests/NodeConfiguration/NodeSettingsTest.cs
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
  src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs
  src/Stratis.Bitcoin/Utilities/Extensions/IPExtensions.cs
Labels: pr-review-low

#1437 Blockstore refactoring
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockRepositoryInMemory.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopIntegration.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepBaseTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepCheckNextChainedBlockExistStepTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepFindBlocksTaskTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepReadBlocksTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepReorganiseTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/LoopTests/BlockStoreLoopStepTryPendingTest.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockPair.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockRepository.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoop.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreLoopStep.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreManager.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreSignaled.cs
  src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepContext.cs
  src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepFindBlocks.cs
  src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/BlockStoreInnerStepReadBlocks.cs
  src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/CheckNextChainedBlockExistStep.cs
  src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/DownloadBlockStep.cs
  src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/ProcessPendingStorageStep.cs
  src/Stratis.Bitcoin.Features.BlockStore/LoopSteps/ReorganiseBlockRepositoryStep.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/FullNodeBuilderTest.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeRunners.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/TestHelper.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/BlockStoreTests.cs
  src/Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeSyncTests.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/BaseRPCControllerTest.cs
  src/Stratis.Bitcoin/Base/ChainState.cs
  src/Stratis.Bitcoin/BlockPulling/StoreBlockPuller.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
  src/Stratis.Bitcoin/Interfaces/IBlockStore.cs
  src/Stratis.BitcoinD/Program.cs
  src/Stratis.StratisD/Program.cs
  src/Stratis.StratisD/Stratis.StratisD.csproj
  src/Stratis.StratisDnsD/Program.cs
Labels: pr-review-critical

#1447 ChainedHeaderTree part 1
  src/NBitcoin/ChainedHeader.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/InitialBlockDownloadTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PowCoinViewRuleTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRuleUnitTestBase.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/ConsensusRulesTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/InitialBlockDownloadState.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/ConsensusRules.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowMiningTest.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/InitialBlockDownloadStateMock.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.Tests.Common/ReflectionExtensions.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/CheckpointsTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs
  src/Stratis.Bitcoin.Tests/NodeConfiguration/ConsensusSettingsTest.cs
  src/Stratis.Bitcoin/Base/Deployments/DeploymentFlags.cs
  src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConsensusSettings.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/Checkpoints.cs
  src/Stratis.Bitcoin/Consensus/ConsensusExceptions.cs
  src/Stratis.Bitcoin/Utilities/Extensions/CollectionExtensions.cs
  src/Stratis.Bitcoin/Utilities/Extensions/CommandLineArgsExtensions.cs
Labels: pr-review-high
