Repository stratisproject/StratisBitcoinFullNode, pull requests merged in 2018-06, with the labels that each got.

#1465 Small Network changes
  src/NBitcoin.Tests/NetworkTests.cs
  src/NBitcoin/Block.cs
  src/NBitcoin/BlockStake.cs
  src/NBitcoin/Consensus.cs
  src/NBitcoin/DNSSeedData.cs
  src/NBitcoin/IBitcoinSerializable.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/Networks.cs
  src/NBitcoin/Networks/BitcoinMain.cs
  src/NBitcoin/Networks/BitcoinRegTest.cs
  src/NBitcoin/Networks/BitcoinTest.cs
  src/NBitcoin/Networks/StratisMain.cs
  src/NBitcoin/Networks/StratisRegTest.cs
  src/NBitcoin/Networks/StratisTest.cs
  src/NBitcoin/PubKey.cs
  src/Stratis.Bitcoin.Tests/Consensus/CheckpointsTest.cs
Labels: pr-review-medium

#1464 [RF][SmartContracts] Create CoinviewRule base class
  src/Stratis.Bitcoin.Features.Consensus.Tests/PosConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/PowConsensusRulesRegistrationTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PowCoinViewRuleTests.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PosCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/PowCoinviewRule.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/Extensions/CoreNodeExtensions.cs
Labels: Refactor, pr-review-high, smart-contracts

#1463 Move settings accessed via NodeSettings to appropriate settings classes
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreCacheTest.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreCache.cs
  src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
  src/Stratis.Bitcoin/P2P/PeerConnector.cs
Labels: pr-review-low

#1431 Remove "loadConfiguration" argument from NodeSettings ctor
  src/Stratis.Bitcoin.Api.Tests/ApiSettingsTest.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/StoreSettingsTest.cs
  src/Stratis.Bitcoin.Features.Dns.Tests/GivenADnsFeature.cs
  src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeRunners.cs
  src/Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs
  src/Stratis.Bitcoin.Tests/NodeConfiguration/NodeSettingsTest.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
  src/Stratis.Bitcoin.Tests/Utilities/Extensions/IPExtensionsTest.cs
  src/Stratis.Bitcoin/Builder/FullNodeBuilder.cs
  src/Stratis.Bitcoin/Builder/FullNodeBuilderNodeSettingsExtension.cs
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/LogSettings.cs
  src/Stratis.BitcoinD/Program.cs
  src/Stratis.BreezeD/Program.cs
  src/Stratis.StratisD/Program.cs
  src/Stratis.StratisDnsD/Program.cs
Labels: pr-review-medium

#1406 Simple Dashboard Feature
  src/Stratis.Bitcoin.FullNode.sln
  src/Stratis.Bitcoin/Controllers/DashboardController.cs
  src/Stratis.Bitcoin/FullNode.cs
Labels: pr-review-low

#1466 Chained tree part 2
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs
  src/Stratis.Bitcoin/Base/BaseFeature.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusExceptions.cs
Labels: pr-review-medium

#1476 Consensus manager removal
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusManager.cs
Labels: pr-review-low

#1477 Coinstaske age tests
  src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Miner/MiningFeature.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin.Tests.Common/ReflectionExtensions.cs
Labels: pr-review-low

#1475 One rewind data instance per block when close to chain tip
  src/Stratis.Bitcoin.Features.Consensus/ConsensusLoop.cs
Labels: pr-review-medium

#1480 Added finalized block height
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.Tests/Base/ChainRepositoryTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin/Base/BaseFeature.cs
  src/Stratis.Bitcoin/Base/ChainRepository.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
Labels: pr-review-medium

#1449 In mempool behaviour use own locks instead of mempool manager locks
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolManagerTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolManager.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolOrphans.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolPerformanceCounter.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolSignaled.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
Labels: pr-review-high

#1456 Explicit implementation of 12 RPC calls in API
  src/Stratis.Bitcoin.Features.Api/MvcBuilderExtensions.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreControllerTests.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/Stratis.Bitcoin.Features.BlockStore.Tests.csproj
  src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusController.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolController.cs
  src/Stratis.Bitcoin.Features.RPC.Tests/Controller/FullNodeControllerTest.cs
  src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
  src/Stratis.Bitcoin.Features.RPC/Converters/BtcDecimalJsonConverter.cs
  src/Stratis.Bitcoin.Features.RPC/Models/GetInfoModel.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Controllers/WatchOnlyWalletController.cs
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Models/WatchOnlyWalletModel.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/AddNodeActionTest.cs
  src/Stratis.Bitcoin.IntegrationTests/RPC/ConsensusActionTests.cs
  src/Stratis.Bitcoin.Tests/Connection/ConnectionManagerControllerTest.cs
  src/Stratis.Bitcoin.Tests/Controllers/NodeControllerTest.cs
  src/Stratis.Bitcoin.Tests/Converters/BtcDecimalJsonConverterTest.cs
  src/Stratis.Bitcoin.Tests/Models/TransactionModelsTest.cs
  src/Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj
  src/Stratis.Bitcoin/Connection/ConnectionManagerController.cs
  src/Stratis.Bitcoin/Controllers/Converters/BtcDecimalJsonConverter.cs
  src/Stratis.Bitcoin/Controllers/Converters/ToStringJsonConverter.cs
  src/Stratis.Bitcoin/Controllers/Models/BlockHeaderModel.cs
  src/Stratis.Bitcoin/Controllers/Models/GetTxOutModel.cs
  src/Stratis.Bitcoin/Controllers/Models/StatusModel.cs
  src/Stratis.Bitcoin/Controllers/Models/TransactionModel.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
Labels: pr-review-medium

#1481 Tests for chained header tree
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1491 Cleanup block definitions
  src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/Comparers/CompareModifiedEntry.cs
  src/Stratis.Bitcoin.Features.Miner/Comparers/CompareTxIterByAncestorCount.cs
  src/Stratis.Bitcoin.Features.Miner/PosBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/TxMemPoolModifiedEntry.cs
  src/Stratis.Bitcoin/Mining/BlockTemplate.cs
Labels: improvement, pr-review-low

#1497 Utilize BlockSize property in the block store queue
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
Labels: pr-review-low

#1498 Added UnconsumedBlocksDataBytes
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
Labels: pr-review-low

#1509 Moved MaxMoney to Consensus
  src/NBitcoin.Tests/NetworkTests.cs
  src/NBitcoin/Block.cs
  src/NBitcoin/BlockHeader.cs
  src/NBitcoin/Consensus.cs
  src/NBitcoin/Networks/BitcoinMain.cs
  src/NBitcoin/Networks/StratisMain.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/CheckPowTransactionRuleTest.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusOptions.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
Labels: pr-review-medium

#1478 Add additional logging and clean up the settings classes
  src/Stratis.Bitcoin.Features.Api/ApiSettings.cs
  src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/InitialBlockDownloadTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/InitialBlockDownloadState.cs
  src/Stratis.Bitcoin.Features.Dns.Tests/GivenAWhitelistManager.cs
  src/Stratis.Bitcoin.Features.Dns/DnsSettings.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolSettings.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.Miner/MinerSettings.cs
  src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs
  src/Stratis.Bitcoin.IntegrationTests.Common/EnvironmentMockUpHelpers/InitialBlockDownloadStateMock.cs
  src/Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.Tests/NodeConfiguration/NodeSettingsTest.cs
  src/Stratis.Bitcoin.Tests/P2P/PeerConnectorTests.cs
  src/Stratis.Bitcoin/Base/BaseFeature.cs
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConsensusSettings.cs
  src/Stratis.Bitcoin/Connection/ConnectionManager.cs
  src/Stratis.Bitcoin/Controllers/NodeController.cs
  src/Stratis.Bitcoin/Utilities/NetworkExtensions.cs
  src/Stratis.StratisDnsD/Program.cs
Labels: pr-review-medium

#1501 Modify delay in inventory sends in mempool
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolBehavior.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolOrphans.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolSignaled.cs
  src/Stratis.Bitcoin.IntegrationTests/MemoryPoolTests.cs
Labels: pr-review-high

#1301 Merge in NBitcoin changes up to v4.0.0.54
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/BlockHeader.cs
  src/NBitcoin/RPC/RPCException.cs
  src/NBitcoin/Transaction.cs
  src/NBitcoin/TransactionBuilder.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
  src/Stratis.Bitcoin.IntegrationTests/BlockStore/RetrieveFromBlockStoreSteps.cs
  src/Stratis.Bitcoin.IntegrationTests/Transactions/TransactionWithNullDataSteps.cs
Labels: pr-review-high

#1515 Adds an ILogger parameter to the TextFileConfiguration Get methods
  src/Stratis.Bitcoin.Features.Api/ApiSettings.cs
  src/Stratis.Bitcoin.Features.BlockStore/StoreSettings.cs
  src/Stratis.Bitcoin.Features.Dns/DnsSettings.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolSettings.cs
  src/Stratis.Bitcoin.Features.Miner/MinerSettings.cs
  src/Stratis.Bitcoin.Features.RPC/RpcSettings.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletSettings.cs
  src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs
  src/Stratis.Bitcoin/Configuration/NodeSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConnectionManagerSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/ConsensusSettings.cs
  src/Stratis.Bitcoin/Configuration/Settings/LogSettings.cs
  src/Stratis.Bitcoin/Configuration/TextFileConfiguration.cs
Labels: pr-review-low

#1519 Cleanup 7
  src/NBitcoin.Tests/util_tests.cs
  src/NBitcoin/BIP39/Wordlist.cs
  src/NBitcoin/BitcoinCore/Coins.cs
  src/NBitcoin/BouncyCastle/crypto/engines/AesEngine.cs
  src/NBitcoin/BouncyCastle/crypto/engines/AesFastEngine.cs
  src/NBitcoin/FileLock.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/Script.cs
  src/NBitcoin/ScriptReader.cs
  src/NBitcoin/Transaction.cs
  src/NBitcoin/TransactionBuilder.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
  src/Stratis.Bitcoin.Features.Consensus/ConsensusStats.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/MemoryPoolTransactionTests.cs
  src/Stratis.Bitcoin.Features.MemoryPool/Fee/BlockPolicyEstimator.cs
  src/Stratis.Bitcoin.Features.MemoryPool/Fee/TxConfirmStats.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolPersistence.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs
  src/Stratis.Bitcoin.Features.MemoryPool/TxMemPool.cs
  src/Stratis.Bitcoin.Features.RPC/Controllers/RPCController.cs
  src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs
  src/Stratis.Bitcoin/Connection/DropNodesBehaviour.cs
Labels: pr-review-low

#1512 Added new test to cover issue #13. Presenting chains with different chain work
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
Labels: pr-review-low

#1521 [RF][SmartContracts] Abstract the AddToBlock method
  src/Stratis.Bitcoin.Features.Miner/BlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PosBlockDefinition.cs
  src/Stratis.Bitcoin.Features.Miner/PowBlockDefinition.cs
Labels: Refactor, improvement, pr-review-medium

#1517 Consensus manager part 2
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreFeature.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreQueue.cs
  src/Stratis.Bitcoin.Features.BlockStore/BlockStoreSignaled.cs
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusManagerTests.cs
  src/Stratis.Bitcoin/Base/ChainHeadersBehavior.cs
  src/Stratis.Bitcoin/Consensus/BlockValidator.cs
  src/Stratis.Bitcoin/Consensus/ChainedHeaderTree.cs
  src/Stratis.Bitcoin/Consensus/ConsensusExceptions.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManger.cs
  src/Stratis.Bitcoin/Interfaces/IBlockStore.cs
  src/Stratis.Bitcoin/Primitives/ChainedHeaderBlock.cs
Labels: pr-review-low

#1424 Integration tests for transaction size limit and double spend failure.
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTransactionOverPolicyByteLimitSpecification_Steps.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification.cs
  src/Stratis.Bitcoin.IntegrationTests/Wallet/SendingTxWithDoubleSpendSpecification_Steps.cs
Labels: pr-review-low

#1527 Remove SetNull() from BlockHeader and make the constructor internal
  src/NBitcoin.Tests/ChainTests.cs
  src/NBitcoin.Tests/ConstructorsForSerializableClassesTest.cs
  src/NBitcoin.Tests/pos_transaction_tests.cs
  src/NBitcoin.Tests/transaction_tests.cs
  src/NBitcoin/BitcoinStream.cs
  src/NBitcoin/Block.cs
  src/NBitcoin/BlockHeader.cs
  src/NBitcoin/ConsensusFactory.cs
  src/NBitcoin/IBitcoinSerializable.cs
  src/NBitcoin/NoSqlRepository.cs
  src/NBitcoin/Transaction.cs
  src/NBitcoin/TransactionBuilder.cs
  src/Stratis.Bitcoin.Features.BlockStore.Tests/BlockStoreTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/InitialBlockDownloadTest.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/CommonRules/PowCoinViewRuleTests.cs
  src/Stratis.Bitcoin.Features.MemoryPool.Tests/FeeTests.cs
  src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs
  src/Stratis.Bitcoin.Features.Notifications.Tests/NotificationsControllerTest.cs
  src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.IntegrationTests/MinerTests.cs
  src/Stratis.Bitcoin.Tests/Base/BestChainSelectorTest.cs
Labels: Refactor, improvement, pr-review-high

#1549 Added endpoint to show smart contract logs
  src/Stratis.Bitcoin/Controllers/DashboardController.cs
  src/Stratis.StratisSmartContractsD/Stratis.StratisSmartContractsD.csproj
  src/Stratis.StratisSmartContractsD/nlog.config
Labels: pr-review-low, smart-contracts

#1513 Chained Header Tree issues 5, 8, 9 initial check in (#1321)
  src/Stratis.Bitcoin.Tests/Consensus/ChainedHeaderTreeTest.cs
  src/Stratis.Bitcoin.Tests/Consensus/ConsensusTestExtensions.cs
Labels: pr-review-low

#1544 Cleanup network usage in NBitcoin #1
  src/NBitcoin.Tests/JsonConverterTests.cs
  src/NBitcoin.Tests/NetworkTests.cs
  src/NBitcoin.Tests/bip32_tests.cs
  src/NBitcoin.Tests/bloom_tests.cs
  src/NBitcoin.Tests/checkblock_tests.cs
  src/NBitcoin.Tests/script_tests.cs
  src/NBitcoin.Tests/sighash_tests.cs
  src/NBitcoin/Block.cs
  src/NBitcoin/BlockHeader.cs
  src/NBitcoin/BlockStake.cs
  src/NBitcoin/Consensus.cs
  src/NBitcoin/ConsensusFactory.cs
  src/NBitcoin/DefaultConsensusfactory.cs
  src/NBitcoin/IBitcoinSerializable.cs
  src/NBitcoin/JsonConverters/BitcoinSerializableJsonConverter.cs
  src/NBitcoin/JsonConverters/Serializer.cs
  src/NBitcoin/Network.cs
  src/NBitcoin/Networks/BitcoinMain.cs
  src/NBitcoin/Networks/StratisMain.cs
  src/NBitcoin/NoSqlRepository.cs
  src/NBitcoin/RPC/RPCClient.cs
  src/NBitcoin/Script.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CalculateStakeRule.cs
  src/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs
  src/Stratis.Bitcoin.Features.Miner/PosMinting.cs
  src/Stratis.Bitcoin/Utilities/DBreezeSerializer.cs
Labels: improvement, pr-review-critical
