Repository stratisproject/StratisBitcoinFullNode, pull requests merged in 2019-03, with the labels that each got.

#3292 [FS] Move transaction building to own file
  src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
  src/Stratis.Features.FederatedPeg/Interfaces/IWithdrawalTransactionBuilder.cs
  src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
  src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
Labels: SideChains

#3295 Fix Ensure_Peer_CanDiscover_Address_From_ConnectedPeers_And_Connect_ToThem
  src/Stratis.Bitcoin.IntegrationTests/Connectivity/ConnectivityTests.cs
  src/Stratis.Bitcoin/P2P/PeerSelector.cs
Labels: Integration/Unit Test

#3262 [SC] Upgrade to Stratis.SmartContracts 1.2.1
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/ContractValidationRuleTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Controllers/SmartContractWalletControllerTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs
  src/Stratis.SmartContracts.CLR.Tests/AuctionTests.cs
  src/Stratis.SmartContracts.CLR.Tests/CallDataSerializerTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractExecutorTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractParametersJsonResolverTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractRefundProcessorTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ExecutorFixture.cs
  src/Stratis.SmartContracts.CLR.Tests/ExecutorSpecification.cs
  src/Stratis.SmartContracts.CLR.Tests/GasMeterTests.cs
  src/Stratis.SmartContracts.CLR.Tests/GasPriceListTests.cs
  src/Stratis.SmartContracts.CLR.Tests/InternalExecutorSpecification.cs
  src/Stratis.SmartContracts.CLR.Tests/InternalExecutorTestFixture.cs
  src/Stratis.SmartContracts.CLR.Tests/LocalExecutorSpecification.cs
  src/Stratis.SmartContracts.CLR.Tests/MeteredPersistenceStrategyTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ObserverTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.SmartContracts.CLR.Tests/SignedCodeCallDataSerializerTests.cs
  src/Stratis.SmartContracts.CLR.Tests/StateTransitionSpecification.cs
  src/Stratis.SmartContracts.CLR.Validation/Stratis.SmartContracts.CLR.Validation.csproj
  src/Stratis.SmartContracts.CLR/BaseMessage.cs
  src/Stratis.SmartContracts.CLR/CallDataSerializer.cs
  src/Stratis.SmartContracts.CLR/CallMessage.cs
  src/Stratis.SmartContracts.CLR/ContractTransferMessage.cs
  src/Stratis.SmartContracts.CLR/ContractTxData.cs
  src/Stratis.SmartContracts.CLR/ExternalCallMessage.cs
  src/Stratis.SmartContracts.CLR/ExternalCreateMessage.cs
  src/Stratis.SmartContracts.CLR/GasPriceList.cs
  src/Stratis.SmartContracts.CLR/ILRewrite/CodeSegment.cs
  src/Stratis.SmartContracts.CLR/InternalCallMessage.cs
  src/Stratis.SmartContracts.CLR/InternalCreateMessage.cs
  src/Stratis.SmartContracts.CLR/InternalExecutor.cs
  src/Stratis.SmartContracts.CLR/Local/ILocalExecutionResult.cs
  src/Stratis.SmartContracts.CLR/Local/LocalExecutionResult.cs
  src/Stratis.SmartContracts.CLR/MeteredPersistenceStrategy.cs
  src/Stratis.SmartContracts.CLR/Metering/GasMeter.cs
  src/Stratis.SmartContracts.CLR/ResultProcessors/ContractRefundProcessor.cs
  src/Stratis.SmartContracts.CLR/ResultProcessors/IContractRefundProcessor.cs
  src/Stratis.SmartContracts.CLR/SignedCodeCallDataSerializer.cs
  src/Stratis.SmartContracts.CLR/SignedCodeContractTxData.cs
  src/Stratis.SmartContracts.CLR/SmartContractState.cs
  src/Stratis.SmartContracts.CLR/StateProcessor.cs
  src/Stratis.SmartContracts.CLR/StateTransitionResult.cs
  src/Stratis.SmartContracts.IntegrationTests/ContractExecutionFailureTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMemoryPoolTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMinerTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletOnPosNetworkTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs
  src/Stratis.SmartContracts.IntegrationTests/SignedContractTests.cs
Labels: smart-contracts

#3308 [FS] Remove leader functionality
  src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationGatewayControllerTests.cs
  src/Stratis.Features.FederatedPeg.Tests/LeaderProviderTests.cs
  src/Stratis.Features.FederatedPeg.Tests/LeaderReceiverTests.cs
  src/Stratis.Features.FederatedPeg.Tests/SignedMultisigTransactionBroadcasterTests.cs
  src/Stratis.Features.FederatedPeg/Controllers/FederationGatewayController.cs
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
  src/Stratis.Features.FederatedPeg/LeaderProvider.cs
  src/Stratis.Features.FederatedPeg/TargetChain/LeaderReceiver.cs
  src/Stratis.Features.FederatedPeg/TargetChain/SignedMultisigTransactionBroadcaster.cs
Labels: SideChains

#3317 [FS] Update FederationGatewayFeature to run in new FN
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
Labels: SideChains

#3346 [SC] DI Smart Contract Consensus Rules
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/AllowedScriptTypeRuleTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/P2PKHNotContractRuleTests.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ISmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/IFullNodeBuilderExtensions.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/Rules/SmartContractPoACoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/SignedContractPoARuleRegistration.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoARuleEngine.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoARuleRegistration.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoS/IFullNodeBuilderExtensions.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoS/Rules/SmartContractPosCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoS/SmartContractPosConsensusRuleEngine.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoS/SmartContractPosRuleRegistration.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoW/IFullNodeBuilderExtensions.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoW/Rules/SmartContractPowCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoW/SmartContractPowConsensusRuleEngine.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoW/SmartContractPowRuleRegistration.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Rules/AllowedScriptTypeRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Rules/P2PKHNotContractRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinViewRuleLogic.cs
  src/Stratis.Bitcoin.Features.SmartContracts/Rules/SmartContractCoinviewRule.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractMempoolValidator.cs
  src/Stratis.Bitcoin/Consensus/DiConsensusRuleEngine.cs
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMinerTests.cs
Labels: smart-contracts

#3351 [FS] Remove internals visible to
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
Labels: SideChains

#3339 [FS] Removing unused params
  src/Stratis.Features.FederatedPeg.Tests/BlockObserverTests.cs
  src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
  src/Stratis.Features.FederatedPeg.Tests/DepositExtractorTests.cs
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
  src/Stratis.Features.FederatedPeg/SourceChain/DepositExtractor.cs
Labels: SideChains

#3311 [FS] FederationWalletTransactionHandler Refactoring
  src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
  src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
  src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
  src/Stratis.Features.FederatedPeg/Wallet/FederationWalletTransactionBuilder.cs
Labels: SideChains

#3354 [FS] Sidechains integration tests with history
  src/Stratis.Bitcoin.FullNode.sln
  src/Stratis.Features.FederatedPeg.IntegrationTests/ContractExecutionTests.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/LeaderTests.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/MiningTests.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/NodeSetupTests.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/SmartContracts/BasicTransfer.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Stratis.Features.FederatedPeg.IntegrationTests.csproj
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/FederatedPegTestExtensions.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/FederatedPegTestHelper.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/MainChainFederationNodeRunner.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainFederationNodeRunner.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainNodeBuilder.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainTestContext.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainUserNodeRunner.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainWithSmartContractsNodeRunner.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/TestFederatedPegBlockDefinition.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/xunit.runner.json
  src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs
Labels: SideChains

#3359 [SC] Support DI configuration via options
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/IFullNodeBuilderExtensions.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/SignedContractPoARuleRegistration.cs
  src/Stratis.Bitcoin.Features.SmartContracts/PoA/SmartContractPoARuleRegistration.cs
  src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/ReflectionVirtualMachineFeature.cs
  src/Stratis.Bitcoin.Features.SmartContracts/SmartContractFeature.cs
  src/Stratis.SmartContracts.Tests.Common/SignedContractPoARunner.cs
  src/Stratis.SmartContracts.Tests.Common/SmartContractPoARunner.cs
  src/Stratis.SmartContracts.Tests.Common/StratisSmartContractNode.cs
  src/Stratis.SmartContracts.Tests.Common/StratisSmartContractPosNode.cs
  src/Stratis.StratisSmartContractsD/Program.cs
Labels: smart-contracts

#3368 [FS] Enable integration tests and ensure nodes run
  src/Stratis.Features.FederatedPeg.IntegrationTests/NodeSetupTests.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainFederationNodeRunner.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainUserNodeRunner.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainWithSmartContractsNodeRunner.cs
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
Labels: SideChains

#3358 [FS] Only perform federation syncing work from a reasonable time
  src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
  src/Stratis.Features.FederatedPeg.Tests/Stratis.Features.FederatedPeg.Tests.csproj
  src/Stratis.Features.FederatedPeg.Tests/xunit.runner.json
  src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs
  src/Stratis.Features.FederatedPeg/Interfaces/IFederationGatewaySettings.cs
  src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
Labels: SideChains

#3374 [FS] Remove mincoinmaturity, always use 1
  src/Stratis.Features.FederatedPeg.IntegrationTests/Utils/SidechainTestContext.cs
  src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationGatewayControllerTests.cs
  src/Stratis.Features.FederatedPeg.Tests/CrossChainTestBase.cs
  src/Stratis.Features.FederatedPeg.Tests/CrossChainTransferStoreTests.cs
  src/Stratis.Features.FederatedPeg/Controllers/FederationGatewayController.cs
  src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs
  src/Stratis.Features.FederatedPeg/Interfaces/IFederationGatewaySettings.cs
  src/Stratis.Features.FederatedPeg/Models/FederationGatewayInfoModel.cs
  src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
Labels: SideChains

#3353 [FS] Sidechains fee comes out of deposits
  src/Stratis.Features.FederatedPeg.Tests/DepositExtractorTests.cs
  src/Stratis.Features.FederatedPeg.Tests/WithdrawalTransactionBuilderTests.cs
  src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs
  src/Stratis.Features.FederatedPeg/SourceChain/DepositExtractor.cs
  src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
  src/Stratis.Features.FederatedPeg/Wallet/FederationWalletTransactionBuilder.cs
Labels: SideChains

#3400 [FS] Remove Leader. Broadcast signed transactions every 10 seconds.
  src/Stratis.Features.FederatedPeg.IntegrationTests/LeaderTests.cs
  src/Stratis.Features.FederatedPeg.Tests/BlockObserverTests.cs
  src/Stratis.Features.FederatedPeg.Tests/ControllersTests/FederationGatewayControllerTests.cs
  src/Stratis.Features.FederatedPeg.Tests/LeaderProviderTests.cs
  src/Stratis.Features.FederatedPeg.Tests/LeaderReceiverTests.cs
  src/Stratis.Features.FederatedPeg.Tests/RestClientsTests/FederationGatewayClientTests.cs
  src/Stratis.Features.FederatedPeg.Tests/SignedMultisigTransactionBroadcasterTests.cs
  src/Stratis.Features.FederatedPeg.Tests/WithdrawalExtractorTests.cs
  src/Stratis.Features.FederatedPeg.Tests/WithdrawalReceiverTests.cs
  src/Stratis.Features.FederatedPeg/Controllers/FederationGatewayController.cs
  src/Stratis.Features.FederatedPeg/FederationGatewayFeature.cs
  src/Stratis.Features.FederatedPeg/LeaderProvider.cs
  src/Stratis.Features.FederatedPeg/Notifications/BlockObserver.cs
  src/Stratis.Features.FederatedPeg/RestClients/FederationGatewayClient.cs
  src/Stratis.Features.FederatedPeg/TargetChain/LeaderReceiver.cs
  src/Stratis.Features.FederatedPeg/TargetChain/PartialTransactionRequester.cs
  src/Stratis.Features.FederatedPeg/TargetChain/SignedMultisigTransactionBroadcaster.cs
  src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalReceiver.cs
Labels: SideChains

#3406 [SC] Reverse commit to lesser version
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Consensus/Rules/ContractValidationRuleTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Controllers/SmartContractWalletControllerTest.cs
  src/Stratis.Bitcoin.Features.SmartContracts.Tests/Stratis.Bitcoin.Features.SmartContracts.Tests.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/Wallet/SmartContractTransactionService.cs
  src/Stratis.SmartContracts.CLR.Tests/AuctionTests.cs
  src/Stratis.SmartContracts.CLR.Tests/CallDataSerializerTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractExecutorTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractParametersJsonResolverTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractRefundProcessorTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ContractTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ExecutorFixture.cs
  src/Stratis.SmartContracts.CLR.Tests/ExecutorSpecification.cs
  src/Stratis.SmartContracts.CLR.Tests/GasMeterTests.cs
  src/Stratis.SmartContracts.CLR.Tests/GasPriceListTests.cs
  src/Stratis.SmartContracts.CLR.Tests/InternalExecutorSpecification.cs
  src/Stratis.SmartContracts.CLR.Tests/InternalExecutorTestFixture.cs
  src/Stratis.SmartContracts.CLR.Tests/LocalExecutorSpecification.cs
  src/Stratis.SmartContracts.CLR.Tests/MeteredPersistenceStrategyTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ObserverTests.cs
  src/Stratis.SmartContracts.CLR.Tests/ReflectionVirtualMachineTests.cs
  src/Stratis.SmartContracts.CLR.Tests/SignedCodeCallDataSerializerTests.cs
  src/Stratis.SmartContracts.CLR.Tests/StateTransitionSpecification.cs
  src/Stratis.SmartContracts.CLR.Validation/Stratis.SmartContracts.CLR.Validation.csproj
  src/Stratis.SmartContracts.CLR/BaseMessage.cs
  src/Stratis.SmartContracts.CLR/CallDataSerializer.cs
  src/Stratis.SmartContracts.CLR/CallMessage.cs
  src/Stratis.SmartContracts.CLR/ContractTransferMessage.cs
  src/Stratis.SmartContracts.CLR/ContractTxData.cs
  src/Stratis.SmartContracts.CLR/ExternalCallMessage.cs
  src/Stratis.SmartContracts.CLR/ExternalCreateMessage.cs
  src/Stratis.SmartContracts.CLR/GasPriceList.cs
  src/Stratis.SmartContracts.CLR/ILRewrite/CodeSegment.cs
  src/Stratis.SmartContracts.CLR/InternalCallMessage.cs
  src/Stratis.SmartContracts.CLR/InternalCreateMessage.cs
  src/Stratis.SmartContracts.CLR/InternalExecutor.cs
  src/Stratis.SmartContracts.CLR/Local/ILocalExecutionResult.cs
  src/Stratis.SmartContracts.CLR/Local/LocalExecutionResult.cs
  src/Stratis.SmartContracts.CLR/MeteredPersistenceStrategy.cs
  src/Stratis.SmartContracts.CLR/Metering/GasMeter.cs
  src/Stratis.SmartContracts.CLR/ResultProcessors/ContractRefundProcessor.cs
  src/Stratis.SmartContracts.CLR/ResultProcessors/IContractRefundProcessor.cs
  src/Stratis.SmartContracts.CLR/SignedCodeCallDataSerializer.cs
  src/Stratis.SmartContracts.CLR/SignedCodeContractTxData.cs
  src/Stratis.SmartContracts.CLR/SmartContractState.cs
  src/Stratis.SmartContracts.CLR/StateProcessor.cs
  src/Stratis.SmartContracts.CLR/StateTransitionResult.cs
  src/Stratis.SmartContracts.IntegrationTests/ContractExecutionFailureTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMemoryPoolTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMinerTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletOnPosNetworkTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletTests.cs
  src/Stratis.SmartContracts.IntegrationTests/SignedContractTests.cs
Labels: smart-contracts

#3422 Just a useful comment
  src/Stratis.Features.FederatedPeg/TargetChain/CrossChainTransferStore.cs
Labels: SideChains

#3423 [FS] Require the Federation IPs parameter
  src/Stratis.Features.FederatedPeg/FederationGatewaySettings.cs
Labels: SideChains

#3424 [FS] Adjusting MaxReorg for CirrusV2 networks
  src/Stratis.Sidechains.Networks/CirrusV2/CirrusMain.cs
  src/Stratis.Sidechains.Networks/CirrusV2/CirrusRegTest.cs
  src/Stratis.Sidechains.Networks/CirrusV2/CirrusTest.cs
Labels: SideChains

#3425 [FS] FederationWalletSyncManager uses a queue
  src/Stratis.Features.FederatedPeg/Wallet/FederationWalletSyncManager.cs
Labels: SideChains

#3434 [FS] Log warning when no outputs to spend, instead of Error
  src/Stratis.Features.FederatedPeg.Tests/WithdrawalTransactionBuilderTests.cs
  src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalTransactionBuilder.cs
  src/Stratis.Features.FederatedPeg/Wallet/FederationWalletTransactionBuilder.cs
Labels: SideChains
